[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
solc = '0.8.19'
out = 'out'
libs = ['lib']
remappings = []

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
base = "${RPC_BASE}"
gnosis = "${RPC_GNOSIS}"
scroll = "${RPC_SCROLL}"

[etherscan]
mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}
optimism={key="${ETHERSCAN_API_KEY_OPTIMISM}",chainId=10}
avalanche={key="${ETHERSCAN_API_KEY_AVALANCHE}",chainId=43114}
polygon={key="${ETHERSCAN_API_KEY_POLYGON}",chainId=137}
arbitrum={key="${ETHERSCAN_API_KEY_ARBITRUM}",chainId=42161}
fantom={key="${ETHERSCAN_API_KEY_FANTOM}",chainId=250}
base={key="${ETHERSCAN_API_KEY_BASE}",chainId=8453}
gnosis={key="${ETHERSCAN_API_KEY_GNOSIS}",chainId=100}
scroll={key="${ETHERSCAN_API_KEY_SCROLL}",chainId=534352}

# See more config options https://github.com/gakonst/foundry/tree/master/config
